deploymentsGeneral: {}
deployments: {}
statefulSetsGeneral: {}
statefulSets: {}
daemonSetsGeneral: {}
daemonSets: {}
configs: {}
services: {}
ingresses: {}
httpRoutes: {}
jobs: {}
generic:
  labels: {}
  annotations: {}
secretRefs: {}
