{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- $defaultedConfig := include "idlefy-universal.deploymentDefaults" (dict "deployment" $deploymentConfig "general" $.Values.deploymentsGeneral) | fromYaml }}
{{- if $defaultedConfig.autoCreateRbac }}
{{- include "idlefy-universal.autoRbac" (dict "deploymentName" $deploymentName "deploymentConfig" $defaultedConfig "root" $) }}
---
{{- end }}
{{- end }}
{{- range $stsName, $stsConfig := .Values.statefulSets }}
{{- $defaultedConfig := include "idlefy-universal.statefulSetDefaults" (dict "statefulSet" $stsConfig "general" $.Values.statefulSetsGeneral) | fromYaml }}
{{- if $defaultedConfig.autoCreateRbac }}
{{- include "idlefy-universal.autoRbac" (dict "deploymentName" $stsName "deploymentConfig" $defaultedConfig "root" $) }}
---
{{- end }}
{{- end }}
{{- range $dsName, $dsConfig := .Values.daemonSets }}
{{- $defaultedConfig := include "idlefy-universal.daemonSetDefaults" (dict "daemonSet" $dsConfig "general" $.Values.daemonSetsGeneral) | fromYaml }}
{{- if $defaultedConfig.autoCreateRbac }}
{{- include "idlefy-universal.autoRbac" (dict "deploymentName" $dsName "deploymentConfig" $defaultedConfig "root" $) }}
---
{{- end }}
{{- end }}
{{- range $jobName, $jobConfig := .Values.jobs }}
{{- $defaultedConfig := include "idlefy-universal.deploymentDefaults" (dict "deployment" $jobConfig "general" $.Values.deploymentsGeneral) | fromYaml }}
{{- if $defaultedConfig.autoCreateRbac }}
{{- include "idlefy-universal.autoRbac" (dict "deploymentName" $jobName "deploymentConfig" $defaultedConfig "root" $) }}
---
{{- end }}
{{- end }}
{{- range $cronJobName, $cronJobConfig := .Values.cronJobs }}
{{- $defaultedConfig := include "idlefy-universal.deploymentDefaults" (dict "deployment" $cronJobConfig "general" $.Values.deploymentsGeneral) | fromYaml }}
{{- if $defaultedConfig.autoCreateRbac }}
{{- include "idlefy-universal.autoRbac" (dict "deploymentName" $cronJobName "deploymentConfig" $defaultedConfig "root" $) }}
---
{{- end }}
{{- end }}
